language: node_js
node_js:
- '5.5'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: bNrkGczufihiGhjrjLjO+CXxPJf+XvSW7iK30XZ4A277pFMHgEW+My5emlpsiIKfNyP6sVjh9EVpKzH8b/jtjy+deNP1Q/x4ysS1qr7ubRqA7a2Z0zm7IEO24Uvl7p/+f0HMuihZHH1cS8QjNhnxm0SeQRPUGPJyDlyJ6cYV4XakW129H853aHod84ZajwP5gaRifg3kR/9UqG1EOSRJ+xa9CJZAslFkTw0as8mmeiKl3XIfg5tEuL54PJbbVhOYifI8s/qrn6TRWwxTOgbUlxOntlLYY19sBR70nW5O/FpfvrBv9eYZEJjFsVfZBbqp7apDMMa11QpRD5qnxtIV2DzNLEc+d4h8GZ7OXmfDz+nYOgyRTZEg5NdQnjXzsJ9A4q35COtXJArYQ7La5RoJJK3bGaro83LhN7tiTuSfFOFE2/2DhPsABARm7YqTAs3EKAP5AwKHbRIca+c9oPJDFwcLQyeEYnnvZcNcwT2HRthqgCfOByjCGy6r+BX7i4b1dqAx/QfSAspk28GlQmaZjdU1fzTYGS5gxP8jlADwXBAuVBua+MUgrKRx0kInRppq12Czo0GS3HMRAZuf99w8C2jiomy8YDLtNgAEt2yhL774nE+x+gmqdiOlOcEsxX/mH4gl5v1xpNSXTu5vDufN7oHyAKyEql5QzSEN63Wsc+I=
  app: insta-exp
  on:
    repo: mathieudutour/insta-bot
